version: '3'

services:
  php-fpm:
    container_name: blog_php
    build:
      context: ./php-fpm
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1"
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ../:/var/www
    user: ${DOCKER_USER}
  nginx:
    container_name: blog_nginx
    build:
      context: ./nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
  mysql:
    container_name: blog_mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - blog_mysql:/var/lib/mysql
volumes:
  blog_mysql:
